---
version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "15 minutes"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "15 minutes"
  
